"""add attendance sessions

Revision ID: 09bee73b8082
Revises: 1fce27f9bc13
Create Date: 2026-08-29 14:57:44.958509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bee73b8082'
down_revision: Union[str, Sequence[str], None] = '1fce27f9bc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('faculty_id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('radius_meters', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ACTIVE', 'ENDED', name='session_status'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_sessions_class_id'), 'attendance_sessions', ['class_id'], unique=False)
    op.create_index('ix_attendance_sessions_class_id_status', 'attendance_sessions', ['class_id', 'status'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_faculty_id'), 'attendance_sessions', ['faculty_id'], unique=False)
    op.create_index('ix_attendance_sessions_starts_at_ends_at_status', 'attendance_sessions', ['starts_at', 'ends_at', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_sessions_starts_at_ends_at_status', table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_faculty_id'), table_name='attendance_sessions')
    op.drop_index('ix_attendance_sessions_class_id_status', table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_class_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    # ### end Alembic commands ###
