"""add academic entities

Revision ID: 883034a9022d
Revises: 19ffe46df3cc
Create Date: 2026-08-29 13:25:00.240773

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '883034a9022d'
down_revision: str | Sequence[str] | None = '19ffe46df3cc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_code'), 'institutions', ['code'], unique=True)
    op.create_table('academic_years',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_academic_years_institution_name')
    )
    op.create_index(op.f('ix_academic_years_institution_id'), 'academic_years', ['institution_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='uq_branches_institution_code')
    )
    op.create_index(op.f('ix_branches_institution_id'), 'branches', ['institution_id'], unique=False)
    op.create_table('faculty',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_employee_id'), 'faculty', ['employee_id'], unique=True)
    op.create_index(op.f('ix_faculty_user_id'), 'faculty', ['user_id'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='uq_subjects_institution_code')
    )
    op.create_index(op.f('ix_subjects_institution_id'), 'subjects', ['institution_id'], unique=False)
    op.create_table('divisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'academic_year_id', 'name', name='uq_divisions_branch_year_name')
    )
    op.create_index(op.f('ix_divisions_academic_year_id'), 'divisions', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_divisions_branch_id'), 'divisions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_divisions_institution_id'), 'divisions', ['institution_id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('faculty_id', sa.Uuid(), nullable=False),
    sa.Column('division_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_academic_year_id'), 'classes', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_classes_division_id'), 'classes', ['division_id'], unique=False)
    op.create_index(op.f('ix_classes_faculty_id'), 'classes', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_classes_institution_id'), 'classes', ['institution_id'], unique=False)
    op.create_index(op.f('ix_classes_subject_id'), 'classes', ['subject_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('prn', sa.String(), nullable=False),
    sa.Column('roll_number', sa.String(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('division_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('face_registered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_academic_year_id'), 'students', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_students_branch_id'), 'students', ['branch_id'], unique=False)
    op.create_index(op.f('ix_students_division_id'), 'students', ['division_id'], unique=False)
    op.create_index(op.f('ix_students_prn'), 'students', ['prn'], unique=True)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('class_enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'student_id', name='uq_class_enrollments_class_student')
    )
    op.create_index(op.f('ix_class_enrollments_class_id'), 'class_enrollments', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_enrollments_student_id'), 'class_enrollments', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_enrollments_student_id'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_class_id'), table_name='class_enrollments')
    op.drop_table('class_enrollments')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_prn'), table_name='students')
    op.drop_index(op.f('ix_students_division_id'), table_name='students')
    op.drop_index(op.f('ix_students_branch_id'), table_name='students')
    op.drop_index(op.f('ix_students_academic_year_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_classes_subject_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_institution_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_faculty_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_division_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_academic_year_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_divisions_institution_id'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_branch_id'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_academic_year_id'), table_name='divisions')
    op.drop_table('divisions')
    op.drop_index(op.f('ix_subjects_institution_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_faculty_user_id'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_employee_id'), table_name='faculty')
    op.drop_table('faculty')
    op.drop_index(op.f('ix_branches_institution_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_academic_years_institution_id'), table_name='academic_years')
    op.drop_table('academic_years')
    op.drop_index(op.f('ix_institutions_code'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
