"""add attendance table and face similarity column

Revision ID: b459e0202afd
Revises: c277665f8ba0
Create Date: 2026-08-29 21:35:02.279206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b459e0202afd'
down_revision: Union[str, Sequence[str], None] = 'c277665f8ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('location_accuracy', sa.Numeric(precision=7, scale=2, asdecimal=False), nullable=False),
    sa.Column('distance_meters', sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=False),
    sa.Column('face_verified', sa.Boolean(), nullable=False),
    sa.Column('face_score', sa.Numeric(precision=6, scale=4, asdecimal=False), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', name='attendance_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_attendance_session_student')
    )
    op.create_index(op.f('ix_attendance_session_id'), 'attendance', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.add_column('attendance_verifications', sa.Column('face_similarity', sa.Numeric(precision=6, scale=4, asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_verifications', 'face_similarity')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_session_id'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
