"""add attendance verifications

Revision ID: c277665f8ba0
Revises: 09bee73b8082
Create Date: 2026-08-29 19:13:36.324337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c277665f8ba0'
down_revision: Union[str, Sequence[str], None] = '09bee73b8082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'LOCATION_VERIFIED', 'FACE_VERIFIED', 'COMPLETED', 'FAILED', 'EXPIRED', name='verification_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_latitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=True),
    sa.Column('location_longitude', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=True),
    sa.Column('location_accuracy_meters', sa.Numeric(precision=7, scale=2, asdecimal=False), nullable=True),
    sa.Column('location_distance_meters', sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_verifications_session_id'), 'attendance_verifications', ['session_id'], unique=False)
    op.create_index('ix_attendance_verifications_session_id_student_id', 'attendance_verifications', ['session_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_attendance_verifications_student_id'), 'attendance_verifications', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_verifications_student_id'), table_name='attendance_verifications')
    op.drop_index('ix_attendance_verifications_session_id_student_id', table_name='attendance_verifications')
    op.drop_index(op.f('ix_attendance_verifications_session_id'), table_name='attendance_verifications')
    op.drop_table('attendance_verifications')
    # ### end Alembic commands ###
